### PR TITLE
Fixed parsing tags errors on problem record and filters

### LINKED ISSUE #366: Fix tags parsing in the Problem Record and Dashboard
* Same way it was fixed in the Programming Problem
* Fix the parsing in the Problem Record
* Also fix it in the dashboard
* Fix it anywhere else

### PR DESCRIPTION
**Pull request by seanquiambao**
filtersfix
problemrecordfix

Should cover every parsing error for every tag used in the website, let me know if I am missing some!

### CODE REVIEW

File: components/ProblemRecord.jsx [hunk 1]
```diff
@@ -69,9 +69,7 @@ const ProblemRecord = () => {
 
     if (cachedProblems !== null) {
       setProblems(cachedProblems);
-      setFilteredProblems(
-        cachedProblems.filter((problem) => allIDs.includes(problem.id))
-      );
+      setFilteredProblems(cachedProblems);
```
Comment (khandrew1) [inline components/ProblemRecord.jsx]: change this back to the filtered cached

**Review by khandrew1 — CHANGES_REQUESTED** [review]

**Review by khandrew1 — APPROVED** [review]
